### Cadastro de Usuário Comum
POST http://localhost:3000/users
Content-Type: application/json


{
    "name": "John Doe",
    "email": "sofia@test.com",
    "password": "123456"
}

### Cadastro de Usuário Partner:
POST http://localhost:3000/patners/users
Content-Type: application/json


{
    "name": "sofia Doe",
    "email": "sada@test.com",
    "password": "123456"
}

### Login de Usuário:
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "sada@test.com",
    "password": "123456"
}

### Criação de Partner:
POST http://localhost:3000/partners
Content-Type: application/json
x-api-token: 777
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJzb2ZpYSBEb2UiLCJlbWFpbCI6InNhZGFAdGVzdC5jb20iLCJyb2xlcyI6WyJQQVJUTkVSIl0sImNyZWF0ZWRBdCI6IjIwMjQtMDYtMjFUMjM6NDI6MjMuNTYxWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMjFUMjM6NDI6MjMuNTYxWiIsImlhdCI6MTcxOTAxMzM5NSwiZXhwIjoxNzE5MDIzMzk1fQ.pESofgheL_hSyEjg-ypy50MpXcjX4z4ZIHzX1MKZJyM

{
    "name": "nanda LTDA"
}

### Listagem de Partners:
GET http://localhost:3000/partners
x-api-token: 777
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJzb2ZpYSBEb2UiLCJlbWFpbCI6InNhZGFAdGVzdC5jb20iLCJyb2xlcyI6WyJQQVJUTkVSIl0sImNyZWF0ZWRBdCI6IjIwMjQtMDYtMjFUMjM6NDI6MjMuNTYxWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMjFUMjM6NDI6MjMuNTYxWiIsImlhdCI6MTcxOTAxMzM5NSwiZXhwIjoxNzE5MDIzMzk1fQ.pESofgheL_hSyEjg-ypy50MpXcjX4z4ZIHzX1MKZJyM


### Criação de Evento:
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json
x-api-token: 777
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJzb2ZpYSBEb2UiLCJlbWFpbCI6InNhZGFAdGVzdC5jb20iLCJyb2xlcyI6WyJQQVJUTkVSIl0sImNyZWF0ZWRBdCI6IjIwMjQtMDYtMjFUMjM6NDI6MjMuNTYxWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMjFUMjM6NDI6MjMuNTYxWiIsImlhdCI6MTcxOTAxMzM5NSwiZXhwIjoxNzE5MDIzMzk1fQ.pESofgheL_hSyEjg-ypy50MpXcjX4z4ZIHzX1MKZJyM

{
    "name": "Evento da nanda - 78 Eve nanda - 7",
    "description": "Evento da nanda - 78",
    "date": "2024-07-15T10:00:00Z",
    "price": 150.2,
    "location": "Rua 1, 123",
    "partnerId": 1
}


### // Recebe id evento após criado

@eventId = {{ createEvent.response.body.id }}


### Listagem de Todos os Eventos
GET http://localhost:3000/events
Content-Type: application/json
x-api-token: 777
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJtYXJ0YUB0ZXN0LmNvbSIsInJvbGVzIjpbIlBBUlRORVIiXSwiY3JlYXRlZEF0IjoiMjAyNC0wNi0yMVQyMzoyMDo1Ni4wMjdaIiwidXBkYXRlZEF0IjoiMjAyNC0wNi0yMVQyMzoyMDo1Ni4wMjdaIiwiaWF0IjoxNzE5MDEyMjM1LCJleHAiOjE3MTkwMjIyMzV9.WIOBzegtum_o7dfn-Vuc_2wHto6U5cEpAoMtZ176aBU

### Buscar um Evento Específico:
GET http://localhost:3000/events/{{ eventId }}
Content-Type: application/json
x-api-token: 777
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJzb2ZpYSBEb2UiLCJlbWFpbCI6InNhZGFAdGVzdC5jb20iLCJyb2xlcyI6WyJQQVJUTkVSIl0sImNyZWF0ZWRBdCI6IjIwMjQtMDYtMjFUMjM6NDI6MjMuNTYxWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMjFUMjM6NDI6MjMuNTYxWiIsImlhdCI6MTcxOTAxMzM5NSwiZXhwIjoxNzE5MDIzMzk1fQ.pESofgheL_hSyEjg-ypy50MpXcjX4z4ZIHzX1MKZJyM

### Edição de Evento:
PUT http://localhost:3000/events/{{ eventId }}
Content-Type: application/json
x-api-token: 777
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJzb2ZpYSBEb2UiLCJlbWFpbCI6InNhZGFAdGVzdC5jb20iLCJyb2xlcyI6WyJQQVJUTkVSIl0sImNyZWF0ZWRBdCI6IjIwMjQtMDYtMjFUMjM6NDI6MjMuNTYxWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMjFUMjM6NDI6MjMuNTYxWiIsImlhdCI6MTcxOTAxMzM5NSwiZXhwIjoxNzE5MDIzMzk1fQ.pESofgheL_hSyEjg-ypy50MpXcjX4z4ZIHzX1MKZJyM

{
    "name": "Evento da nanda - 66 Evento da nanda - 66Evento da nanda - 66Evento da nanda - 66Evento da nanda -  ",
    "description": "Evento da nanda - 66",
    "date": "2024-07-15T10:00:00Z",
    "price": 150.2,
    "location": "Rua 1, 123",
    "partnerId": 1
}

### Remoção de Evento:
DELETE http://localhost:3000/events/{{ eventId }}
Content-Type: application/json
x-api-token: 777
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJzb2ZpYSBEb2UiLCJlbWFpbCI6InNhZGFAdGVzdC5jb20iLCJyb2xlcyI6WyJQQVJUTkVSIl0sImNyZWF0ZWRBdCI6IjIwMjQtMDYtMjFUMjM6NDI6MjMuNTYxWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMjFUMjM6NDI6MjMuNTYxWiIsImlhdCI6MTcxOTAxMzM5NSwiZXhwIjoxNzE5MDIzMzk1fQ.pESofgheL_hSyEjg-ypy50MpXcjX4z4ZIHzX1MKZJyM

### Listagem de Todos os Spots do Evento:
GET http://localhost:3000/events/{{ eventId }}/spots
x-api-token: 777
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJzb2ZpYSBEb2UiLCJlbWFpbCI6InNhZGFAdGVzdC5jb20iLCJyb2xlcyI6WyJQQVJUTkVSIl0sImNyZWF0ZWRBdCI6IjIwMjQtMDYtMjFUMjM6NDI6MjMuNTYxWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMjFUMjM6NDI6MjMuNTYxWiIsImlhdCI6MTcxOTAxMzM5NSwiZXhwIjoxNzE5MDIzMzk1fQ.pESofgheL_hSyEjg-ypy50MpXcjX4z4ZIHzX1MKZJyM

### Criação de Spot do Evento:
# @name createSpot
POST http://localhost:3000/events/{{ eventId }}/spots
Content-Type: application/json
x-api-token: 777
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJzb2ZpYSBEb2UiLCJlbWFpbCI6InNhZGFAdGVzdC5jb20iLCJyb2xlcyI6WyJQQVJUTkVSIl0sImNyZWF0ZWRBdCI6IjIwMjQtMDYtMjFUMjM6NDI6MjMuNTYxWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMjFUMjM6NDI6MjMuNTYxWiIsImlhdCI6MTcxOTAxMzM5NSwiZXhwIjoxNzE5MDIzMzk1fQ.pESofgheL_hSyEjg-ypy50MpXcjX4z4ZIHzX1MKZJyM

{
    "name": "A3"
}

### // Recebe id evento após criado

@spotName = {{ createSpot.response.body.name }}

### Reserva de Evento:
POST http://localhost:3000/events/{{ eventId }}/reserve
Content-Type: application/json
x-api-token: 777
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiJzb2ZpYSBEb2UiLCJlbWFpbCI6InNhZGFAdGVzdC5jb20iLCJyb2xlcyI6WyJQQVJUTkVSIl0sImNyZWF0ZWRBdCI6IjIwMjQtMDYtMjFUMjM6NDI6MjMuNTYxWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMjFUMjM6NDI6MjMuNTYxWiIsImlhdCI6MTcxOTAxMzM5NSwiZXhwIjoxNzE5MDIzMzk1fQ.pESofgheL_hSyEjg-ypy50MpXcjX4z4ZIHzX1MKZJyM

{
    "spots": ["{{ spotName }}"],
    "ticket_kind": "full",
    "email": "test@test.com"
}