GET http://localhost:3000/users 

### Cadastro de Usuário Comum
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "nanda@test.com",
    "password": "123456"
}

### Cadastro de Usuário Partner:
POST http://localhost:3000/patners/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "nanda@test.com",
    "password": "123456"
}

### Login de Usuário:
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "nanda@test.com",
    "password": "123456"
}

### Criação de Partner:
POST http://localhost:3000/partners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJuYW5kYUB0ZXN0LmNvbSIsInJvbGVzIjpbIlBBUlRORVIiXSwiY3JlYXRlZEF0IjoiMjAyNC0wNi0yMVQwMjozMTo0NS40MzlaIiwidXBkYXRlZEF0IjoiMjAyNC0wNi0yMVQwMjozMTo0NS40MzlaIiwiaWF0IjoxNzE4OTM3MTE5LCJleHAiOjE3MTg5NDcxMTl9.jn6m9aGt4h2EuhDXNyS9FJDksR7lroYvdujACpqXRnw

{
    "name": "nanda LTDA"
}

### Listagem de Partners:
GET http://localhost:3000/partners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJuYW5kYUB0ZXN0LmNvbSIsInJvbGVzIjpbIlBBUlRORVIiXSwiY3JlYXRlZEF0IjoiMjAyNC0wNi0yMVQwMjozMTo0NS40MzlaIiwidXBkYXRlZEF0IjoiMjAyNC0wNi0yMVQwMjozMTo0NS40MzlaIiwiaWF0IjoxNzE4OTM3MTE5LCJleHAiOjE3MTg5NDcxMTl9.jn6m9aGt4h2EuhDXNyS9FJDksR7lroYvdujACpqXRnw


### Criação de Evento:
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJuYW5kYUB0ZXN0LmNvbSIsInJvbGVzIjpbIlBBUlRORVIiXSwiY3JlYXRlZEF0IjoiMjAyNC0wNi0yMVQwMjozMTo0NS40MzlaIiwidXBkYXRlZEF0IjoiMjAyNC0wNi0yMVQwMjozMTo0NS40MzlaIiwiaWF0IjoxNzE4OTM3MTE5LCJleHAiOjE3MTg5NDcxMTl9.jn6m9aGt4h2EuhDXNyS9FJDksR7lroYvdujACpqXRnw

{
    "name": "Evento da nanda - 78 Eve nanda - 7",
    "description": "Evento da nanda - 78",
    "date": "2024-07-15T10:00:00Z",
    "price": 150.2,
    "location": "Rua 1, 123",
    "partnerId": 1
}


### // Recebe id evento após criado

@eventId = {{ createEvent.response.body.id }}


### Listagem de Todos os Eventos
GET http://localhost:3000/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJuYW5kYUB0ZXN0LmNvbSIsInJvbGVzIjpbIlBBUlRORVIiXSwiY3JlYXRlZEF0IjoiMjAyNC0wNi0yMVQwMjozMTo0NS40MzlaIiwidXBkYXRlZEF0IjoiMjAyNC0wNi0yMVQwMjozMTo0NS40MzlaIiwiaWF0IjoxNzE4OTM3MTE5LCJleHAiOjE3MTg5NDcxMTl9.jn6m9aGt4h2EuhDXNyS9FJDksR7lroYvdujACpqXRnw

### Buscar um Evento Específico:
GET http://localhost:3000/events/{{ eventId }}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJuYW5kYUB0ZXN0LmNvbSIsInJvbGVzIjpbIlBBUlRORVIiXSwiY3JlYXRlZEF0IjoiMjAyNC0wNi0yMVQwMjozMTo0NS40MzlaIiwidXBkYXRlZEF0IjoiMjAyNC0wNi0yMVQwMjozMTo0NS40MzlaIiwiaWF0IjoxNzE4OTM3MTE5LCJleHAiOjE3MTg5NDcxMTl9.jn6m9aGt4h2EuhDXNyS9FJDksR7lroYvdujACpqXRnw

### Edição de Evento:
PUT http://localhost:3000/events/{{ eventId }}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJuYW5kYUB0ZXN0LmNvbSIsInJvbGVzIjpbIlBBUlRORVIiXSwiY3JlYXRlZEF0IjoiMjAyNC0wNi0yMVQwMjozMTo0NS40MzlaIiwidXBkYXRlZEF0IjoiMjAyNC0wNi0yMVQwMjozMTo0NS40MzlaIiwiaWF0IjoxNzE4OTM3MTE5LCJleHAiOjE3MTg5NDcxMTl9.jn6m9aGt4h2EuhDXNyS9FJDksR7lroYvdujACpqXRnw

{
    "name": "Evento da nanda - 66 Evento da nanda - 66Evento da nanda - 66Evento da nanda - 66Evento da nanda -  ",
    "description": "Evento da nanda - 66",
    "date": "2024-07-15T10:00:00Z",
    "price": 150.2,
    "location": "Rua 1, 123",
    "partnerId": 1
}

### Remoção de Evento:
DELETE http://localhost:3000/events/{{ eventId }}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJuYW5kYUB0ZXN0LmNvbSIsInJvbGVzIjpbIlBBUlRORVIiXSwiY3JlYXRlZEF0IjoiMjAyNC0wNi0yMFQwMDowOTo0OS40MTRaIiwidXBkYXRlZEF0IjoiMjAyNC0wNi0yMFQwMDowOTo0OS40MTRaIiwiaWF0IjoxNzE4ODQyNzQ3LCJleHAiOjE3MTg4NTI3NDd9.tgUfi_fGOKhg080lDpoV6nfbM1d_3pjNX5WKWrEYrSU

### Listagem de Todos os Spots do Evento:
GET http://localhost:3000/events/{{ eventId }}/spots

### Criação de Spot do Evento:
# @name createSpot
POST http://localhost:3000/events/{{ eventId }}/spots
Content-Type: application/json

{
    "name": "A3"
}

### // Recebe id evento após criado

@spotName = {{ createSpot.response.body.name }}

### Reserva de Evento:
POST http://localhost:3000/events/{{ eventId }}/reserve
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJuYW5kYUB0ZXN0LmNvbSIsInJvbGVzIjpbIlBBUlRORVIiXSwiY3JlYXRlZEF0IjoiMjAyNC0wNi0yMVQwMjozMTo0NS40MzlaIiwidXBkYXRlZEF0IjoiMjAyNC0wNi0yMVQwMjozMTo0NS40MzlaIiwiaWF0IjoxNzE4OTM3MTE5LCJleHAiOjE3MTg5NDcxMTl9.jn6m9aGt4h2EuhDXNyS9FJDksR7lroYvdujACpqXRnw

{
    "spots": ["{{ spotName }}"],
    "ticket_kind": "456",
    "email": "test@test.com"
}