GET http://localhost:3000/users 

### Usuario Comum
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "mardos1824@test.com",
    "password": "123456"
}

### Usuario Partner
POST http://localhost:3000/patners/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "nanda@test.com",
    "password": "123456"
}

### Usuario Partner
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "marta@test.com",
    "password": "123456"
}

### create Partner
POST http://localhost:3000/partners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoibmFuZGFAdGVzdC5jb20iLCJyb2xlcyI6WyJQQVJUTkVSIl0sImNyZWF0ZWRBdCI6IjIwMjQtMDYtMTZUMDA6NDU6MzIuMTgxWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMTZUMDA6NDU6MzIuMTgxWiIsImlhdCI6MTcxODQ5ODc1NSwiZXhwIjoxNzE4NTA4NzU1fQ.X4prgOS8N8WJbEoJnwIOfxZxg4mo0FFDkwa54QgiyXc

{
    "name": "nanda ltda"
}

### list Partner
GET http://localhost:3000/partners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoibmFuZGFAdGVzdC5jb20iLCJyb2xlcyI6WyJQQVJUTkVSIl0sImNyZWF0ZWRBdCI6IjIwMjQtMDYtMTZUMDA6NDU6MzIuMTgxWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDYtMTZUMDA6NDU6MzIuMTgxWiIsImlhdCI6MTcxODQ5ODc1NSwiZXhwIjoxNzE4NTA4NzU1fQ.X4prgOS8N8WJbEoJnwIOfxZxg4mo0FFDkwa54QgiyXc


### Cadastrar Evento
POST http://localhost:3000/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJtYXJ0YUB0ZXN0LmNvbSIsInJvbGVzIjpbIlVTRVIiXSwiY3JlYXRlZEF0IjoiMjAyNC0wNi0xNVQyMTowOToxMy42ODFaIiwidXBkYXRlZEF0IjoiMjAyNC0wNi0xNVQyMTowOToxMy42ODFaIiwiaWF0IjoxNzE4NTAwMzQzLCJleHAiOjE3MTg1MTAzNDN9.DKORwF9coELRGX_0f7i5B5_p-jEF9dEkeETnQzrMUrY

{
    "name": "Evento da nanda - 8",
    "description": "Evento da nanda - 8",
    "date": "2024-06-15T23:21:34.60",
    "location": "Rua 1, 123",
    "partnerId": 1
}

### Listar Evento
GET http://localhost:3000/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJtYXJ0YUB0ZXN0LmNvbSIsInJvbGVzIjpbIlVTRVIiXSwiY3JlYXRlZEF0IjoiMjAyNC0wNi0xNVQyMTowOToxMy42ODFaIiwidXBkYXRlZEF0IjoiMjAyNC0wNi0xNVQyMTowOToxMy42ODFaIiwiaWF0IjoxNzE4NTAwMzQzLCJleHAiOjE3MTg1MTAzNDN9.DKORwF9coELRGX_0f7i5B5_p-jEF9dEkeETnQzrMUrY