services:

  app-nestjs:
    build: .
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/home/node/app
    depends_on:
      - db-mysql

  db-mysql:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: partner1
      # ports:
      #   - 3306:3306
    volumes:
      #  - ./.docker/dbdata:/var/lib/mysql                #Para persistir os dados do banco de dados.
      - ./.docker/mysql:/docker-entrypoint-initdb.d #Para scripts de inicialização do banco de dados.
